# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# ---------------- #
#   Main Configs   #
#   Site Settings  #
# ---------------- #
baseurl:
url: https://github.com/xinerd # the base hostname & protocol for your site
date_format: "ordinal"
title: 启明星
subtitle: "算法，数据结构"
description: "随时随地准备推翻自己的观点。"
keywords: 算法, Shin, xinerd, Java
favicon: favicon.ico # Image must be in assets/images
timezone: America/New_York
encoding: "utf-8"
side_bar_repo_limit: 5 # Sidebar to show popular repo


# ---------------- #
#      Author      #
# ---------------- #
author: Shin Ming
name: Shin Ming
organization: fmachine
organization_url: xin.fmachine.cn
location: Boston, US
email: m.xinerd@gmail.com
company: fmachine
company_url: xin.fmachine.cn
# github_url: https://github.com/xinerd

# ---------------- #
#      Jekyll      #
#  Build settings  #
# ---------------- #
markdown: kramdown
kramdown:
  input: GFM
  enable_coderay: true
highlighter: rouge
# Pagination
paginate: 10
# paginate_path: 'page:num'
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
#  - jekyll-sitemap
#  - jekyll-feed

#     - jekyll-html-pipeline
#     - jekyll-mentions
# source:      .
# destination: ./_site

defaults: []

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /about
    label: About



# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#    Analytics     #
# ---------------- #
analytics :
  provider : google
  google :
      tracking_id : 'UA-86879677-1'

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: xinerd
# disqus_username: xinerd
# 在使用 disqus 的时候可点击显示多说评论框
# lazy_load_duoshuo: true
# Disque
disque: xinerd.disqus.com

# ---------------- #
#      Socials     #
# ---------------- #
github_username: xinerd
douban_username: xinerd
facebook_username: xinerd
weibo_username: xinerd
zhihu_username: xinerd
twitter_username: xinerdm
url_github: https://github.com/xinerd
url_linkedin: https://www.linkedin.com/in/xinerd
url_weibo: http://weibo.com/xinerd
url_zhihu: http://www.zhihu.com/people/xinerd

# For about.html. Fell free to create your own!
skill_software_keywords: [Java, SQL, Algorithm, Data Structure, OOP, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, PHP, Boostrap]
skill_mobile_app_keywords: [Cordova, Phonegap, Android, Reverse Engineering]
personal_keywords: [ex-IBMer, Optimistic, Easy-going, Ambitious, Travel, Cooking]